# kubectl apply -f app.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  # creationTimestamp: null
  name: mw-kube-apm-python-elastic
  namespace: python-demo
spec:
  selector:
    matchLabels:
      app: mw-kube-apm-python-elastic
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mw-kube-apm-python-elastic
        k8s-app: mw-kube-apm-python-elastic
      # creationTimestamp: null
    spec:
      containers:
        - command: ["/bin/sh"]
          args: ["-c", "middleware-run python app.py"]
          env:
            - name: MW_SERVICE_NAME
              value: "python-elastic-k8s"
            - name: MW_AGENT_SERVICE
              value: mw-service.mw-agent-ns.svc.cluster.local
            - name: MW_API_KEY
              value: ycppepesamhvpjnquasfafasfashhxhkmkgqd
            - name: MW_TARGET
              value: https://<uid>.middleware.io:443
            - name: MW_DEBUG_LOG_FILE
              value: "true"
            - name: MW_CONSOLE_EXPORTER
              value: "true"
          #   - name: MYSQL_HOST
          #     value: "mysql.mw-agent-ns-fktzp.svc.cluster.local"
          image: ghcr.io/middleware-labs/demo-apm-python-elastic:latest
          imagePullPolicy: Always
          name: mw-kube-agent
          resources: {}
          ports:
          - containerPort: 4000
      restartPolicy: Always