# kubectl apply -f app.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  name: mw-kube-apm
  namespace: squareops-test
spec:
  selector:
    matchLabels:
      app: mw-app
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mw-app
        k8s-app: mw-app
      creationTimestamp: null
    spec:
      containers:
        - command: ["/bin/sh"]
          args: ["-c", "middleware-apm run python3 manage.py runserver"]
          env:
            # - name: MW_AGENT_SERVICE
            #   value: mw-service.mw-agent-ns.svc.cluster.local
            - name: MIDDLEWARE_CONFIG_FILE
              value: ./middleware.ini
            - name: DJANGO_SETTINGS_MODULE
              value: helloworld.settings
          image: ghcr.io/middleware-labs/django-test
          imagePullPolicy: Always
          name: mw-kube-agent
          resources: {}
          ports:
          - containerPort: 8000
      restartPolicy: Always