version: '3.8'

services:
  django:
    build: .
    volumes:
      - ./static:/static
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "8080:80"
    depends_on:
      - django
